In [12]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
#vocab size
vocab_size=10000

In [4]:
onehotrep=[one_hot(words,vocab_size)for words in sent]

In [5]:
onehotrep

[[726, 290, 8726, 4954],
 [726, 290, 8726, 7867],
 [726, 3059, 8726, 545],
 [4553, 1641, 6936, 1220, 513],
 [4553, 1641, 6936, 1220, 1641],
 [4411, 726, 8901, 8726, 2536],
 [6853, 8205, 4700, 1220]]

In [6]:
#word_embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 
import pandas as pd

In [7]:
# we pad the sequences
sent_len=8
sents=pad_sequences(onehotrep,padding="pre",maxlen=sent_len)# can use post as well for 0's at the end
print(sents)

[[   0    0    0    0  726  290 8726 4954]
 [   0    0    0    0  726  290 8726 7867]
 [   0    0    0    0  726 3059 8726  545]
 [   0    0    0 4553 1641 6936 1220  513]
 [   0    0    0 4553 1641 6936 1220 1641]
 [   0    0    0 4411  726 8901 8726 2536]
 [   0    0    0    0 6853 8205 4700 1220]]


In [8]:
#we use word2vec
dim=10 #no of feature
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_len))
model.compile('adam','mse')

C:\Users\admin\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.predict(sents)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step


array([[[-1.2407888e-02, -2.9305592e-03, -1.3924550e-02, -3.2293785e-02,
         -1.8509403e-03, -3.7352335e-02,  1.0992549e-02,  7.4212439e-03,
         -5.9435852e-03, -3.3831596e-03],
        [-1.2407888e-02, -2.9305592e-03, -1.3924550e-02, -3.2293785e-02,
         -1.8509403e-03, -3.7352335e-02,  1.0992549e-02,  7.4212439e-03,
         -5.9435852e-03, -3.3831596e-03],
        [-1.2407888e-02, -2.9305592e-03, -1.3924550e-02, -3.2293785e-02,
         -1.8509403e-03, -3.7352335e-02,  1.0992549e-02,  7.4212439e-03,
         -5.9435852e-03, -3.3831596e-03],
        [-1.2407888e-02, -2.9305592e-03, -1.3924550e-02, -3.2293785e-02,
         -1.8509403e-03, -3.7352335e-02,  1.0992549e-02,  7.4212439e-03,
         -5.9435852e-03, -3.3831596e-03],
        [-3.0582262e-02,  3.6706436e-02, -2.3376549e-02, -7.5062513e-03,
          9.5175393e-03, -2.3725618e-02, -4.0821910e-02, -3.1932615e-02,
          2.2631910e-02, -1.1847243e-03],
        [-2.9798770e-02,  1.7817866e-02,  2.4037588e-02,  2.